export const GET_COMMENT = 'GET COMMENT';
export const GET_COMMENT_SAGA = 'GET COMMENT SAGA';

export const INSERT_COMMENT_SAGA = 'INSERT COMMENT SAGA';

export const UPDATE_COMMENT_SAGA = 'UPDATE COMMENT SAGA';

export const DELETE_COMMENT_SAGA = 'DELETE COMMENT SAGA';