export const SHOW_DRAWER = 'SHOW DRAWER';
export const HIDE_DRAWER = 'HIDE DRAWER';

export const SET_CONTENT_DRAWER = 'SET CONTENT EDIT PROJECT DRAWER';
export const SET_SUBMIT_DRAWER = 'SET SUBMIT EDIT PROJECT DRAWER';
