export const GET_ISSUE_DETAIL = 'GET ISSUE DETAIL';
export const GET_ISSUE_DETAIL_SAGA = 'GET ISSUE DETAIL SAGA';

export const UPDATE_ISSUE_DETAIL_FIELD = 'UPDATE ISSUE DETAIL FIELD';

export const UPDATE_ISSUE_DETAIL_SAGA = 'UPDATE ISSUE DETAIL SAGA';

export const DELETE_ISSUE_DETAIL_SAGA = 'DELETE ISSUE DETAIL SAGA';

export const CREATE_ISSUE_DETAIL_SAGA = 'CREATE ISSUE DETAIL SAGA';

export const GET_ALL_PRIORITY = 'GET ALL PRIORITY';
export const GET_ALL_PRIORITY_SAGA = 'GET ALL PRIORITY SAGA';

export const GET_ALL_STATUS = 'GET ALL STATUS';
export const GET_ALL_STATUS_SAGA = 'GET ALL STATUS SAGA';

export const GET_ALL_TYPE_TASK = 'GET ALL TYPE TASK';
export const GET_ALL_TYPE_TASK_SAGA = 'GET ALL TYPE TASK SAGA';

export const UPDATE_STATUS_ISSUE_SAGA = 'UPDATE STATUS ISSUE SAGA';