export const GET_ALL_PROJECT_CATEGORY = 'GET ALL PROJECT CATEGORY';
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET ALL PROJECT CATEGORY SAGA';

export const CREATE_PROJECT = 'CREATE PROJECT';
export const CREATE_PROJECT_SAGA = 'CREATE PROJECT SAGA';

export const GET_ALL_PROJECT = 'GET ALL PROJECT';
export const GET_ALL_PROJECT_SAGA = 'GET ALL PROJECT SAGA';

export const ASSIGN_USER_TO_PROJECT_SAGA = 'ASSIGN USER TO PROJECT SAGA';

export const REMOVE_USER_FROM_PROJECT_SAGA = 'REMOVE USER FROM PROJECT SAGA';

export const GET_PROJECT_DETAIL = 'GET PROJECT DETAIL';

export const GET_PROJECT_DETAIL_API = 'GET PROJECT DETAIL API';
export const GET_PROJECT_DETAIL_API_SAGA = 'GET PROJECT DETAIL API SAGA';

export const EDIT_PROJECT_DETAIL_SAGA = 'EDIT PROJECT DETAIL SAGA';

export const DELETE_PROJECT_DETAIL_SAGA = 'DELETE PROJECT DETAIL SAGA';