export const USER_LOGIN = 'USER LOGIN';

export const USER_LOGIN_SAGA = 'USER LOGIN SAGA';

export const GET_USER_BY_KEYWORD = 'GET USER BY KEYWORD';
export const GET_USER_BY_KEYWORD_SAGA = 'GET USER BY KEYWORD SAGA';

export const SEARCH_USER_BY_KEYWORD = 'SEARCH USER BY KEYWORD';
export const SEARCH_USER_BY_KEYWORD_SAGA = 'SEARCH USER BY KEYWORD SAGA';

export const GET_ALL_USER = 'GET ALL USER';
export const GET_ALL_USER_SAGA = 'GET ALL USER SAGA';

export const UPDATE_USER = 'UPDATE USER';
export const UPDATE_USER_SAGA = 'UPDATE USER SAGA';

export const DELETE_USER = 'DELETE USER';
export const DELETE_USER_SAGA = 'DELETE USER SAGA';

export const REGISTER_USER_SAGA = 'REGISTER USER SAGA';
